config/routes.rb
Rails.application.routes.draw do
  
  
  resources :products
  resources :users

  root :to => "static_pages#home"
  post 'sessions/new', to: 'sessions#create'
  get '/products', to: 'products#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/about', to: 'static_pages#about'

  get '/find', to: 'static_pages#contact'


  resources :password_resets,     only: [:new, :create, :edit, :update]
  get 'password_resets/new', to:  'password_resets#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :check_expiration, only: [:edit, :update]
  before_action :get_user,   only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]


  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email])
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Email com instruções enviado"
      redirect_to root_url
    else
      flash.now[:danger] = "Email não encontrado"
      render 'new'
    end
  end

  def edit
  end

  def update
    if params[:user][:password].empty?                  # Case (3)
      @user.errors.add(:password, "Não pode estar em branco!")
      render 'edit'
    elsif @user.update_attributes(user_params)          # Case (4)
      log_in @user
      flash[:success] = "Senha atualizada!"
      redirect_to @user
    else
      render 'edit'                                     # Case (2)
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def get_user
    @user = User.find_by(email: params[:email])
  end



  def valid_user
    unless (@user &&   @user.authenticated?(:reset, params[:id]))
      redirect_to root_url
    end
  end


  def check_expiration
    if @user.password_reset_expired?
      flash[:danger] = "Redefinição de senha expirou!"
      redirect_to new_password_reset_url
    end
  end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, 'Recuperação de senha') %>
<h1>Recuperar senha</h1>

<div class="row">
 
    <%= form_for(@user, url: password_reset_path(params[:id])) do |form| %>
      <%= render 'shared/error_messages' %>

      <%= hidden_field_tag :email, @user.email %>

      <%= form.label :password %>
      <%= form.password_field :password%>

      <%= form.label :password_confirmation, "Confirmation" %>
      <%= form.password_field :password_confirmation%>

      <%= f.submit "Atualizar senha"%>
    <% end %>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Forgot password") %>
<h1>Recuperar senha</h1>

<div class="row">
    <%= form_for(:password_reset, url: password_resets_path) do |form| %>
      <%= form.label :email, "E-mail" %>
      <%= form.email_field :email %>

      <%= form.submit "Enviar"%>
    <% end %>
  </div>
</div>