config/routes.rb
Rails.application.routes.draw do
  
  
  resources :products
  resources :users

  root :to => "static_pages#home"
  post 'sessions/new', to: 'sessions#create'
  get '/products', to: 'products#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/about', to: 'static_pages#about'

  get '/find', to: 'static_pages#contact'


  resources :password_resets,     only: [:new, :create, :edit, :update]
  get 'password_resets/new', to:  'password_resets#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pé de Pizza</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  

  <body>
    
    <div class="nav">
      <%= link_to 'Pé de Pizza', root_path, class: "title" %>
     
     <div class="menu">
      <% if !current_user %>
          <%= link_to 'Login', login_path, class: "button"%>

      <% end %>
      <% if admin_user_logged?(@user) %>
        <%= link_to 'Ver usuários', users_path, class: "button" %>
      <% end %>
        <%= link_to 'Home', root_path, class: "button" %>
      <%= link_to 'Ver cardápio', products_path, class:"button"  %>
      <% if current_user %>
          <%= link_to 'Meu perfil', current_user, class:"button" %>

      <% end %>
      <%= link_to 'Quem somos?', about_path, class:"button"  %>
      <%= link_to 'Fale conosco', find_path, class:"button" %>
      <%if current_user %>
        <%= link_to 'Sair', logout_path, method: :delete, class:"button" %> 
      <% end %>
      
      </div>
    </div>
    <%= yield %>
    <footer class="rodape">
    <h2>Atendemos apenas na ilha do governador</h2>
    </footer>
   
   
  </body>
</html>